language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "msgjt-github"
    branches:
      - master
      - develop
notifications:
  email: false
  on_success: never
  on_failure: always
script:
  - sonar-scanner
jdk:
  - oraclejdk8

